### ISSUE TITLE
[DISCUSSION] folder and file structure

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#12]

**Comment by ZenaMel** [comment]
# Folder Structure
![image](https://user-images.githubusercontent.com/47085752/82132240-f1e36680-97dd-11ea-85d9-f94811d02e97.png)

**Comment by ZenaMel** [comment]
# Folder Structure - With Files
![image](https://user-images.githubusercontent.com/47085752/82132257-1d665100-97de-11ea-9258-ccbb32f669e5.png)

**Comment by martinisiu** [comment]
Agree with this format. I think its clean and works well
