### ISSUE TITLE
Combine all suggested commands into a table

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#40]
commands -> pinned messages on #software-design

layout:

| Command | Effect |
| ------------- | ------------- |
| lazystarter startproject [name] base=[base] | Creates a directory with the name and base specified by user |
| ... | ... |
| ... | ... |
| ... | ... |

**Comment by martinisiu** [comment]
| Command | Effect |
| lazystarter startproject [name] base=[base] | Creates a directory with the name and base specified by user |

**Comment by ZenaMel** [comment]
Someone should just create a TableOfCommands.md file and put the table with all commands in there.
@esu2020 Would like like to take care of it? I know it's not a coding kind of task but crucial nonetheless.

**Comment by ZenaMel** [comment]
@AT1452 Your commit e57fdae for PR #48 is good but I need you to create a new PR without your other changes in it.

**Comment by ZenaMel** [comment]
closed by #50
