### ISSUE TITLE
basic project scaffolding command with language specific gitignore

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#55]
`lazystarter basic [PROJECT NAME] gitignore="python"`
create folder with src folder and Python.gitignore file

**Comment by AT1452** [comment]
What's the difference between this issue and #56?

**Comment by meta-boy** [comment]
Personally I would approach it like:
1. adding submodule (https://github.com/github/gitignore) to the repo.
2. whenever any command on `lazystarter` is used, check for updates on the repo mentioned above, `try` to pull for changes and proceed further.
3. regular flow of the commands

**Comment by ZenaMel** [comment]
yep you're right, got duplicates here. Need to clean up issues anyway so will do that. Thanks for pointing it out. Discussion on this topic continues on your PR.
